# Generated by Django 5.0.1 on 2024-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
